# docker-compose.yaml
version: '3.8'
services:
  nginx:
    container_name: nginx
    restart: always
    tty: true
    image: nginx
    user: root
    volumes:
     - ./nginx:/etc/nginx/conf.d
    ports:
     - 80:80

  jenkins:
    container_name: jenkins
    restart: always
    tty: true
    image: jenkins/jenkins
    privileged: true
    user: root
    ports:
    #  - 8080:8080
     - 50000:50000
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  sonarqube:
    container_name: sonarqube
    restart: always
    tty: true
    image: sonarqube:latest
    privileged: true
    user: root
    ports:
      - 9000:9000
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarQube_data:/opt/SonarQube/data
      - sonarQube_extensions:/opt/SonarQube/extensions
      - sonarQube_logs:/opt/SonarQube/logs
    
volumes:
  jenkins:
  sonarQube_data:
  sonarQube_extensions:
  sonarQube_logs:
